apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bred
  namespace: flux-system
spec:
  chart:
    spec:
      version: "1.0.0"
  valuesFrom:
    - kind: ConfigMap
      name: redis-values
  # values:
  #   common:
  #     ip: 10.0.0.132
  #   helloworld:
  #     replicas: 1
  #     port: 8080
  #     image:
  #       name: nginx
  #       tag: latest