apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - ../../base/bred
# patchesStrategicMerge:
#   - bred-patch.yaml
configMapGenerator:
  - name: bred-patch
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml